server:
  port: 8080

spring:
  application:
    name: formula-management
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/formula?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.jianhua.fm.**.entity

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    com.jianhua.fm: debug